/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tresenraya;

import java.awt.Color;

/**
 *
 * @author Anthony
 */
public class ventana extends javax.swing.JFrame {

    /**
     * Creates new form ventana
     */
    public ventana() {
        initComponents();
        llenar();
        pnlO.setBackground(Color.WHITE);
        pnlX.setBackground(Color.yellow);
        diagonal1.setVisible(false);
        diagonal2.setVisible(false);
        izqver.setVisible(false);
        derver.setVisible(false);
        mediohor.setVisible(false);
        mediover.setVisible(false);
        abajo.setVisible(false);
        arriba.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        diagonal2 = new javax.swing.JLabel();
        diagonal1 = new javax.swing.JLabel();
        mediover = new javax.swing.JPanel();
        derver = new javax.swing.JPanel();
        arriba = new javax.swing.JPanel();
        abajo = new javax.swing.JPanel();
        mediohor = new javax.swing.JPanel();
        izqver = new javax.swing.JPanel();
        b00 = new javax.swing.JButton();
        b01 = new javax.swing.JButton();
        b02 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        b20 = new javax.swing.JButton();
        b21 = new javax.swing.JButton();
        b22 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        pnlX = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jx = new javax.swing.JLabel();
        pnlO = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jo = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        fondo1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        diagonal2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dia2.png"))); // NOI18N
        jPanel1.add(diagonal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, -1, -1));

        diagonal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dia1.png"))); // NOI18N
        jPanel1.add(diagonal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, -1, -1));

        mediover.setBackground(new java.awt.Color(255, 0, 0));
        mediover.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout medioverLayout = new javax.swing.GroupLayout(mediover);
        mediover.setLayout(medioverLayout);
        medioverLayout.setHorizontalGroup(
            medioverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        medioverLayout.setVerticalGroup(
            medioverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        jPanel1.add(mediover, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        derver.setBackground(new java.awt.Color(255, 0, 0));
        derver.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout derverLayout = new javax.swing.GroupLayout(derver);
        derver.setLayout(derverLayout);
        derverLayout.setHorizontalGroup(
            derverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        derverLayout.setVerticalGroup(
            derverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        jPanel1.add(derver, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        arriba.setBackground(new java.awt.Color(255, 0, 0));
        arriba.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout arribaLayout = new javax.swing.GroupLayout(arriba);
        arriba.setLayout(arribaLayout);
        arribaLayout.setHorizontalGroup(
            arribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        arribaLayout.setVerticalGroup(
            arribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(arriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 320, 10));

        abajo.setBackground(new java.awt.Color(255, 0, 0));
        abajo.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout abajoLayout = new javax.swing.GroupLayout(abajo);
        abajo.setLayout(abajoLayout);
        abajoLayout.setHorizontalGroup(
            abajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        abajoLayout.setVerticalGroup(
            abajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(abajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 310, 10));

        mediohor.setBackground(new java.awt.Color(255, 0, 0));
        mediohor.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout mediohorLayout = new javax.swing.GroupLayout(mediohor);
        mediohor.setLayout(mediohorLayout);
        mediohorLayout.setHorizontalGroup(
            mediohorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        mediohorLayout.setVerticalGroup(
            mediohorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(mediohor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 320, 10));

        izqver.setBackground(new java.awt.Color(255, 0, 0));
        izqver.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout izqverLayout = new javax.swing.GroupLayout(izqver);
        izqver.setLayout(izqverLayout);
        izqverLayout.setHorizontalGroup(
            izqverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        izqverLayout.setVerticalGroup(
            izqverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        jPanel1.add(izqver, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        b00.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        b00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b00ActionPerformed(evt);
            }
        });
        jPanel1.add(b00, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 20, 109, 97));

        b01.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        b01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b01ActionPerformed(evt);
            }
        });
        jPanel1.add(b01, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 20, 109, 97));

        b02.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        b02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b02ActionPerformed(evt);
            }
        });
        jPanel1.add(b02, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 20, 109, 97));

        b12.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12ActionPerformed(evt);
            }
        });
        jPanel1.add(b12, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 123, 109, 97));

        b11.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });
        jPanel1.add(b11, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 123, 109, 97));

        b10.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });
        jPanel1.add(b10, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 123, 109, 97));

        b20.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        b20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b20ActionPerformed(evt);
            }
        });
        jPanel1.add(b20, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 226, 109, 97));

        b21.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        b21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b21ActionPerformed(evt);
            }
        });
        jPanel1.add(b21, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 226, 109, 97));

        b22.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        b22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b22ActionPerformed(evt);
            }
        });
        jPanel1.add(b22, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 226, 109, 97));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 390, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("X");

        jx.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jx.setForeground(new java.awt.Color(255, 51, 51));
        jx.setText("0");

        javax.swing.GroupLayout pnlXLayout = new javax.swing.GroupLayout(pnlX);
        pnlX.setLayout(pnlXLayout);
        pnlXLayout.setHorizontalGroup(
            pnlXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlXLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(jx)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        pnlXLayout.setVerticalGroup(
            pnlXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlXLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jx))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 204));
        jLabel2.setText("O");

        jo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jo.setForeground(new java.awt.Color(51, 0, 204));
        jo.setText("0");

        javax.swing.GroupLayout pnlOLayout = new javax.swing.GroupLayout(pnlO);
        pnlO.setLayout(pnlOLayout);
        pnlOLayout.setHorizontalGroup(
            pnlOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jo)
                .addGap(36, 36, 36))
        );
        pnlOLayout.setVerticalGroup(
            pnlOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jo))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pnlX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 160, 160));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 255));
        jButton1.setText("Juego Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 3, 18)); // NOI18N
        jLabel4.setText("TRES EN RAYA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b00ActionPerformed
        // TODO add your handling code here:
        turnoar();
        l.rayar(matriz, diagonal1, 7, 0, 0);
        l.rayar(matriz, arriba, 1, 0, 0);
        l.rayar(matriz, izqver, 4, 0, 0);
        
        if(l.ejecutar(b00, 0, 0, matriz, jx, jo)==1){
            reiniciar();
        }
    }//GEN-LAST:event_b00ActionPerformed

    private void b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12ActionPerformed
 turnoar();
        
        l.rayar(matriz, derver, 6, 1,2);
                l.rayar(matriz, mediohor, 2, 1, 2);

        if(l.ejecutar(b12, 1,2, matriz, jx, jo)==1){
            reiniciar();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_b12ActionPerformed

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
        // TODO add your handling code here:
        turnoar();
        l.rayar(matriz, diagonal2, 8, 1,1);
        l.rayar(matriz, diagonal1, 7, 1, 1);
        l.rayar(matriz, mediover, 5, 1, 1);
        l.rayar(matriz, mediohor, 2, 1, 1);
        if(l.ejecutar(b11, 1,1, matriz, jx, jo)==1){
            reiniciar();
        }
    }//GEN-LAST:event_b11ActionPerformed

    private void b22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b22ActionPerformed
        // TODO add your handling code here:
        turnoar();
        l.rayar(matriz, mediover, 2, 2,2);
        l.rayar(matriz, diagonal1, 7, 2,2);
        l.rayar(matriz, derver, 6, 2, 2);
        l.rayar(matriz, abajo, 3, 2, 2);
        if(l.ejecutar(b22, 2,2, matriz, jx, jo)==1){
            reiniciar();
        }
    }//GEN-LAST:event_b22ActionPerformed

    private void b01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b01ActionPerformed
        // TODO add your handling code here:
        turnoar();
        l.rayar(matriz, arriba, 1, 0, 1);
        l.rayar(matriz, mediohor, 2, 0, 1);
        l.rayar(matriz, mediover, 5, 0, 1);
        if(l.ejecutar(b01, 0,1, matriz, jx, jo)==1){
            reiniciar();
        }
    }//GEN-LAST:event_b01ActionPerformed

    private void b02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b02ActionPerformed
        // TODO add your handling code here:
        turnoar();
        l.rayar(matriz, diagonal2, 8, 0,2);
        l.rayar(matriz, arriba, 1, 0, 2);
        l.rayar(matriz, derver, 6, 0, 2);
        
        if(l.ejecutar(b02, 0,2, matriz, jx, jo)==1){
            reiniciar();
        }
    }//GEN-LAST:event_b02ActionPerformed

    private void b20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b20ActionPerformed
        // TODO add your handling code here:
        turnoar();
        l.rayar(matriz, diagonal2, 8, 2,0);
                l.rayar(matriz, abajo, 2, 2,0);
        l.rayar(matriz, izqver, 4, 2, 0);
        l.rayar(matriz, abajo, 3, 2, 0);
        if(l.ejecutar(b20, 2,0, matriz, jx, jo)==1){
            reiniciar();
        } 
    }//GEN-LAST:event_b20ActionPerformed

    private void b21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b21ActionPerformed
        // TODO add your handling code here:
        turnoar();
        l.rayar(matriz, abajo, 2, 2,1);
        l.rayar(matriz, mediover, 5, 2, 1);
        l.rayar(matriz, abajo, 3, 2, 1);
        if(l.ejecutar(b21, 2,1, matriz, jx, jo)==1){
            reiniciar();
        } 
    }//GEN-LAST:event_b21ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
        // TODO add your handling code here:
        turnoar();
        l.rayar(matriz, mediohor, 2, 1, 0);
        l.rayar(matriz, izqver, 4, 1, 0);
        if(l.ejecutar(b10, 1,0, matriz, jx, jo)==1){
            reiniciar();
        } 
    }//GEN-LAST:event_b10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        reiniciar();
    }//GEN-LAST:event_jButton1ActionPerformed
int matriz[][]=new int[3][3];
public void llenar(){
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            matriz[i][j]=(j+10)*(i+10);
        }
    }
}
Jugar l=new Jugar(0,0,0);

public void turnoar(){
    if(l.getTurno()==1){
        pnlX.setBackground(Color.yellow);
        pnlO.setBackground(Color.white);
    }
    if(l.getTurno()==0){
        pnlX.setBackground(Color.white);
        pnlO.setBackground(Color.yellow);
    }
}
public void reiniciar(){
    llenar();
    b00.setText("");
    b00.setEnabled(true);
    b01.setText("");
    b01.setEnabled(true);
    b02.setText("");
    b02.setEnabled(true);
    b10.setText("");
    b10.setEnabled(true);
    b11.setText("");
    b11.setEnabled(true);
    b12.setText("");
    b12.setEnabled(true);
    b20.setText("");
    b20.setEnabled(true);
    b21.setText("");
    b21.setEnabled(true);
    b22.setText("");
    b22.setEnabled(true);
    diagonal1.setVisible(false);
        diagonal2.setVisible(false);
        izqver.setVisible(false);
        derver.setVisible(false);
        mediohor.setVisible(false);
        mediover.setVisible(false);
        abajo.setVisible(false);
        arriba.setVisible(false);
    
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abajo;
    private javax.swing.JPanel arriba;
    private javax.swing.JButton b00;
    private javax.swing.JButton b01;
    private javax.swing.JButton b02;
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b20;
    private javax.swing.JButton b21;
    private javax.swing.JButton b22;
    private javax.swing.JPanel derver;
    private javax.swing.JLabel diagonal1;
    private javax.swing.JLabel diagonal2;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondo1;
    private javax.swing.JPanel izqver;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jo;
    private javax.swing.JLabel jx;
    private javax.swing.JPanel mediohor;
    private javax.swing.JPanel mediover;
    private javax.swing.JPanel pnlO;
    private javax.swing.JPanel pnlX;
    // End of variables declaration//GEN-END:variables
}

